export const PODLIST = [
"associazione-ruoli-pf",
"catalog-services",
"contrattualizzazione",
"configurazione-prodotto-ccretail-cdm",
"attivazione-ccretail-cdm",
"feu-catalogo",
"feuhomepage",
"dematerialization-service",
"registrazione-oad",
"libretti-aperture-riepilogo",
"riepilogo-operazione-cdm",
"verifichePreliminari",
"verifiche-preliminari-cdm",
"post-processamento-attivazione",
"cross-selling",
"libretti-apertura-attivazione",
"libretti-aperture-creazionePratica",
"libretti-apertura-configurazioneProdotto",
"libretti-aperture-associazioneRuoli",
"libretti-postvendita-attivazione",
"libretti-postvendita-associazioneruoli",
"libretti-postvendita-configurazioneprodotto",
"oss-apertura-attivazione",	
"oss-apertura-configurazioneProdotto",	
"oss-apertura-associazioneRuoli",
"libretti-aperture-configurazioneprodotto-cdm",
"buoni-emissione-calcolatore",
"buoni-emissioni-attivazione",
"buoni-emissioni-associazioneRuoli",
"buoni-emissioni-configurazioneProdotto",
"buoni-emissioni-creazionePratica",
"pdr-postvendita-configurazioneprodotto",
"buoni-postvendita-configurazioneprodotto",
"buoni-postvendita-recesso-rimborso",
"risparmio-semplice",
"conti-configura-prodotto",
"conti-intervista-cliente",
"conti-perfezionamento-pratica-retail",
"telepass-attivazione",
"conti-selezione-carta",
"intervista-commerciale-cdm",
"intervista-commerciale-retail",
"mifid-homepage",
"mifid-contratto",
"mifid-classificazione",
"mifid-attivazione",
"mifid-profilazione",
"buoni-emissioni-configurazioneprodotto-cdm",
"buoni-emissioni-attivazione-cdm",
"libretti-aperture-attivazione-cdm",
"libretti-aperture-configurazioneprodotto-cdm",
"frontend-carte",
"ppevo-retail-attivazione",
"ppevo-annullo-connettizzazione",
"ppevo-connettizzazione-attivazione",
"tras-controtransazione",
"ppevo-connettizzazione-configurazioneprodotto",
"tras-attivazione",
"simulatore-nliquidita",
"associazione-sim",
"fid-cdm",
"richiesta-qrcode",
"libretti-postvendita-configurazioneprodotto-cdm",
"pdr-postvendita-configurazioneprodtto-cdm",
"pdr-postvendita-attivazione-cdm",
"pdr-postvendita-configurazioneprodotto-cdm",
"pdr-postvendita-attivazione-cdm",
]

export const OCP_PODS=[
{pod:"associazione-ruoli-pf",upstreamRelease:"release-associazione-ruoli-pf-upstream",upstreamDeploy:"deploy-associazione-ruoli-pf-upstream"},
{pod:"buoni-emissioni-associazioneRuoli",upstreamRelease:"release-buoni-emissioni-associazioneruoli-upstream",upstreamDeploy:"deploy-buoni-emissioni-associazioneruoli-upstream"},
{pod:"buoni-emissioni-attivazione",upstreamRelease:"release-buoni-emissioni-attivazione-upstream",upstreamDeploy:"deploy-buoni-emissioni-attivazione-upstream"},
{pod:"buoni-emissione-calcolatore",upstreamRelease:"release-buoni-emissioni-calcolatore-upstream",upstreamDeploy:"deploy-buoni-emissioni-calcolatore-upstream"},
{pod:"buoni-emissioni-configurazioneprodotto",upstreamRelease:"release-feu-buoni-emissioni-configurazioneprodotto-upstream",upstreamDeploy:"deploy-feu-buoni-emissioni-configurazioneprodotto-upstream"},
{pod:"buoni-emissioni-creazionePratica",upstreamRelease:"release-buoni-emissioni-creazionepratica-upstream",upstreamDeploy:"deploy-buoni-emissioni-creazionepratica-upstream"},
{pod:"buoni-postvendita-configurazioneprodotto",upstreamRelease:"release-buoni-postvendita-configurazioneprodotto-upstream",upstreamDeploy:"deploy-buoni-postvendita-configurazioneprodotto-upstream"},
{pod:"catalog-services",upstreamRelease:"release-frontend-commonsteps-catalog-services-upstream",upstreamDeploy:"deploy-frontend-commonsteps-catalog-services-upstream"},
{pod:"conti-selezione-carta",upstreamRelease:"release-conti-selezione-carta",upstreamDeploy:"deploy-conti-selezione-carta"},
{pod:"conti-perfezionamento-pratica-retail",upstreamRelease:"release-conti-perfezionamento-pratica-retail-upstream",upstreamDeploy:"deploy-conti-perfezionamento-pratica-retail-upstream"},
{pod:"contrattualizzazione",upstreamRelease:"release-contrattualizzazione-upstream",upstreamDeploy:"deploy-contrattualizzazione-upstream"},
{pod:"feu-catalog",upstreamRelease:"release-feu-catalog-upstream",upstreamDeploy:"deploy-feu-catalogo-upstream"},
{pod:"libretti-apertura-attivazione",upstreamRelease:"release-libretti-aperture-attivazione-upstream",upstreamDeploy:"deploy-feu-libretti-aperture-attivazione-upstream"},
{pod:"libretti-apertura-configurazioneProdotto",upstreamRelease:"release-libretti-aperture-configurazioneprodotto-upstream",upstreamDeploy:"deploy-libretti-aperture-configurazioneprodotto-upstream"},
{pod:"libretti-aperture-associazioneRuoli",upstreamRelease:"release-libretti-aperture-associazioneruoli-upstream",upstreamDeploy:"deploy-libretti-aperture-associazioneruoli-upstream"},
{pod:"libretti-aperture-creazionePratica",upstreamRelease:"release-libretti-aperture-creazionepratica-upstream",upstreamDeploy:"deploy-libretti-aperture-creazionepratica-upstream"},
{pod:"libretti-postvendita-associazioneruoli",upstreamRelease:"release-libretti-postvendita-associazioneruoli-upstream",upstreamDeploy:"deploy-libretti-postvendita-associazioneruoli-upstream"},
{pod:"libretti-postvendita-attivazione",upstreamRelease:"release-libretti-postvendita-attivazione-upstream",upstreamDeploy:"deploy-libretti-postvendita-attivazione-upstream"},
{pod:"libretti-postvendita-configurazioneprodotto",upstreamRelease:"release-libretti-postvendita-configurazioneprodotto-upstream",upstreamDeploy:"deploy-libretti-postvendita-configurazioneprodotto-upstream"},
{pod:"oss-apertura-associazioneRuoli",upstreamRelease:"release-oss-apertura-associazioneRuoli-upstream",upstreamDeploy:"deploy-oss-apertura-associazioneRuoli-upstream"},
{pod:"oss-apertura-attivazione",upstreamRelease:"release-oss-aperture-attivazione-upstream",upstreamDeploy:"deploy-oss-aperture-attivazione-upstream"},
{pod:"oss-apertura-configurazioneProdotto",upstreamRelease:"release-oss-apertura-configurazioneProdotto-upstream",upstreamDeploy:"deploy-oss-apertura-configurazioneProdotto-upstream"},
{pod:"pdr-postvendita-configurazioneprodotto",upstreamRelease:"release-pdr-postvendita-configurazioneprodotto-upstream",upstreamDeploy:"deploy-pdr-postvendita-configurazioneprodotto-upstream"},
{pod:"post-processamento-attivazione",upstreamRelease:"release-post-processamento-attivazione-upstream",upstreamDeploy:"deploy-post-processamento-attivazione-upstream"},
{pod:"richiesta-qrcode",upstreamRelease:"release-richiesta-qrcode-upstream",upstreamDeploy:"deploy-richiesta-qrcode-upstream"},
{pod:"riepilogo-operazione",upstreamRelease:"release-feu-libretti-aperture-riepilogo-upstream",upstreamDeploy:"deploy-feu-libretti-aperture-riepilogo-upstream"},
{pod:"risparmio-semplice",upstreamRelease:"release-risparmio-semplice-upstream",upstreamDeploy:"deploy-risparmio-semplice-upstream"},
{pod:"verifichePreliminari",upstreamRelease:"release-verifichepreliminari-upstream",upstreamDeploy:"deploy-verifichepreliminari-upstream"},
{pod:"verifiche-preliminari-cdm",upstreamRelease:"release-verifiche-preliminari-cdm-upstream",upstreamDeploy:"deploy-verifiche-preliminari-cdm-upstream"},
{pod:"simulatore-nliquidita",upstreamRelease:"release-simulatore-nliquidita-upstream",upstreamDeploy:"deploy-simulatore-nliquidita-upstream"},
{pod:"X",upstreamRelease:"X",upstreamDeploy:"X"},
]

export const HELM_PODS=[
{pod:"associazione-sim",sourceRepository:"https://gitlab.alm.poste.it/FrontEnd_CommonSteps/associazione-sim.git",pipeLineRelease:"associazione-sim-release",upstreamDeploy:"deploy-associazione-sim-upstream"},
{pod:"attivazione-ccretail-cdm",sourceRepository:"https://gitlab.alm.poste.it/frontend_conti/attivazione-ccretail-cdm.git",pipeLineRelease:"attivazione-ccretail-cdm-release",upstreamDeploy:"deploy-attivazione-ccretail-cdm-upstream"},
{pod:"buoni-emissioni-attivazione-cdm",sourceRepository:"http://gitlab.alm.poste.it/FrontEnd_Buoni/buoni-emissioni-attivazione-cdm",pipeLineRelease:"buoni-emissioni-attivazione-cdm-release",upstreamDeploy:"deploy-buoni-emissioni-attivazione-cdm-upstream"},
{pod:"buoni-emissioni-configurazioneprodotto-cdm",sourceRepository:"http://gitlab.alm.poste.it/FrontEnd_Buoni/buoni-emissioni-configurazioneprodotto-cdm",pipeLineRelease:"buoni-emissioni-configurazioneprodotto-cdm-release",upstreamDeploy:"deploy-buoni-emissioni- configurazioneprodotto-cdm-upstream"},
{pod:"configurazione-prodotto-ccretail-cdm",sourceRepository:"https://gitlab.alm.poste.it/frontend_conti/configurazione-prodotto-ccretail-cdm",pipeLineRelease:"configurazione-prodotto-ccretail-cdm-release",upstreamDeploy:"deploy-configurazione-prodotto-ccretail-upstream"},
{pod:"conti-configura-prodotto",sourceRepository:"https://gitlab.alm.poste.it/frontend_conti/conti-configura-prodotto.git",pipeLineRelease:"release-conti-configura-prodotto-pipeline",upstreamDeploy:"deploy-conti-configura-prodotto-upstream"},
{pod:"cross-selling",sourceRepository:"http://gitlab.alm.poste.it/FrontEnd_CommonSteps/cross-selling.git",pipeLineRelease:"cross-selling-release",upstreamDeploy:"deploy-cross-selling-upstream"},
{pod:"fid-cdm",sourceRepository:"https://gitlab.alm.poste.it/FrontEnd_CommonSteps/fid-cdm.git",pipeLineRelease:"fid-cdm-release",upstreamDeploy:"deploy-fid-cdm-upstream"},	 	
{pod:"frontend-carte",sourceRepository:"https://gitlab.alm.poste.it/FrontEnd_Carte/frontend-carte",pipeLineRelease:"frontend-carte-release",upstreamDeploy:"deploy-frontend-carte-upstream"},
{pod:"intervista-commerciale-cdm",sourceRepository:"http://gitlab.alm.poste.it/FrontEnd_CommonSteps/intervista-commerciale-cdm.git",pipeLineRelease:"intervista-commerciale-cdm-release",upstreamDeploy:"deploy-intervista-commerciale-cdm-upstream"},
{pod:"intervista-commerciale-retail",sourceRepository:"https://gitlab.alm.poste.it/frontend_conti/intervista-commerciale-retail.git",pipeLineRelease:"intervista-commerciale-retail-release",upstreamDeploy:"deploy-intervista-commerciale-retail-upstream"},
{pod:"key-vault-services",sourceRepository:"https://gitlab.alm.poste.it/FrontEnd_CommonSteps/key-vault-services.git",pipeLineRelease:"key-vault-services-release",upstreamDeploy:"deploy-key-vault-services-upstream"},
{pod:"lanciatore-fase",sourceRepository:"https://gitlab.alm.poste.it/FrontEnd_CommonSteps/lanciatore-fase",pipeLineRelease:"release-lanciatore-fase-pipeline",upstreamDeploy:"deploy-lanciatore-fase-upstream"},
{pod:"libretti-aperture-attivazione-cdm",sourceRepository:"http://gitlab.alm.poste.it/FrontEnd_Libretti/libretti-aperture-attivazione-cdm.git",pipeLineRelease:"release-libretti-aperture-attivazione-cdm-pipeline",upstreamDeploy:"deploy-libretti-aperture-attivazione-cdm-upstream"},
{pod:"libretti-aperture-configurazioneprodotto-cdm",sourceRepository:"http://gitlab.alm.poste.it/FrontEnd_Libretti/libretti-aperture-configurazioneprodotto-cdm.git",pipeLineRelease:"release-libretti-aperture-configurazioneprodotto-cdm-pipeline",upstreamDeploy:"deploy-libretti-aperture-configurazioneprodotto-cdm-upstream"},
{pod:"libretti-postvendita-attivazione-cdm",sourceRepository:"https://gitlab.alm.poste.it/FrontEnd_Libretti/libretti-postvendita-attivazione-cdm.git",pipeLineRelease:"release-libretti-postvendita-attivazione-cdm-pipeline",upstreamDeploy:"deploy-libretti-postvendita-attivazione-cdm-upstream"},
{pod:"libretti-postvendita-configurazioneprodotto-cdm",sourceRepository:"https://gitlab.alm.poste.it/FrontEnd_Libretti/libretti-postvendita-configurazioneprodotto-cdm.git",pipeLineRelease:"release-libretti-postvendita-configurazioneprodotto-cdm-pipeline",upstreamDeploy:"deploy-libretti-postvendita-configurazioneprodotto-cdm-upstream"},
{pod:"mifid-attivazione",sourceRepository:"http://gitlab.alm.poste.it/frontend_mifid/mifid-attivazione.git",pipeLineRelease:"mifid-attivazione-release",upstreamDeploy:"deploy-mifid-attivazione-upstream"},
{pod:"mifid-classificazione",sourceRepository:"http://gitlab.alm.poste.it/frontend_mifid/mifid-classificazione.git",pipeLineRelease:"mifid-classificazione-release",upstreamDeploy:"deploy-mifid-classificazione-upstream"},
{pod:"mifid-homepage",sourceRepository:"http://gitlab.alm.poste.it/frontend_mifid/mifid-homepage.git",pipeLineRelease:"mifid-homepage-release",upstreamDeploy:"deploy-mifid-homepage-upstream"},
{pod:"mifid-profilazione",sourceRepository:"http://gitlab.alm.poste.it/frontend_mifid/mifid-profilazione.git",pipeLineRelease:"mifid-profilazione-release",upstreamDeploy:"deploy-mifid-profilazione-upstream"},
{pod:"pdr-postvendita-attivazione-cdm",sourceRepository:"https://gitlab.alm.poste.it/FrontEnd_Buoni/pdr-postvendita-attivazione-cdm.git",pipeLineRelease:"release-pdr-postvendita-attivazione-cdm-pipeline",upstreamDeploy:"deploy-pdr-postvendita-attivazione-cdm-upstream"},
{pod:"ppevo-annullo-connettizzazione",sourceRepository:"https://gitlab.alm.poste.it/FrontEnd_Carte/ppevo-annullo-connettizzazione.git",pipeLineRelease:"ppevo-annullo-connettizzazione-release",upstreamDeploy:"deploy-ppevo-annullo-connettizzazione-upstream"},
{pod:"ppevo-retail-attivazione",sourceRepository:"https://gitlab.alm.poste.it/FrontEnd_Carte/ppevo-retail-attivazione.git",pipeLineRelease:"ppevo-retail-attivazione-release",upstreamDeploy:"deploy-ppevo-retail-attivazione-upstream"},
{pod:"propositore-commerciale-retail",sourceRepository:"https://gitlab.alm.poste.it/frontend_conti/propositore-commerciale-retail.git",pipeLineRelease:"propositore-commerciale-retail-release",upstreamDeploy:"deploy-propositore-commerciale-retail-upstream"},
{pod:"riepilogo-operazione-cdm",sourceRepository:"http://gitlab.alm.poste.it/FrontEnd_CommonSteps/riepilogo-operazione-cdm.git",pipeLineRelease:"riepilogo-operazione-cdm-release",upstreamDeploy:"deploy-riepilogo-operazione-cdm-upstream"},
{pod:"tras-attivazione",sourceRepository:"http://gitlab.alm.poste.it/FrontEnd_Libretti/tras-attivazione.git",pipeLineRelease:"release-tras-attivazione-pipeline",upstreamDeploy:"deploy-tras-attivazione-upstream"},
{pod:"tras-controtransazione",sourceRepository:"https://gitlab.alm.poste.it/FrontEnd_Libretti/tras-controtransazione.git",pipeLineRelease:"release-tras-controtransazione-pipeline",upstreamDeploy:"deploy-tras-controtransazione-upstream"},
{pod:"X",sourceRepository:"X",pipeLineRelease:"X",upstreamDeploy:"X"},
]

export const OWNERS = [
    {
        name:"MC",
        selected:false
    },
    {
        name:"RI",
        selected:false
    },
    {
        name:"SZ",
        selected:false
    },
    {
        name:"AM",
        selected:false
    },
    {
        name:"VT",
        selected:false
    },
    {
        name:"PC",
        selected:false
    },
    {
        name:"ST",
        selected:false
    },
    {
        name:"FB",
        selected:false
    },
    {
        name:"DM",
        selected:false
    },
    {
        name:"KQ",
        selected:false
    },
    {
        name:"MDB",
        selected:false
    },
    {
        name:"DG",
        selected:false
    },
]

/*
verifiche-preliminari-cdm 1.44.1 25175-25178,
buoni-emissioni-associazioneRuoli 1.44.3 25182, 
libretti-postvendita-configurazioneprodotto-cdm 1.44.5,
buoni-emissioni-configurazioneprodotto 1.44.0,
simulatore-nliquidita 1.44.0,
conti-selezione-carta 1.44.0,
attivazione-ccretail-cdm 1.44.3 25144,
associazione-ruoli-pf 1.44.2 25141-25154 
*/